### PR TITLE
samples: don't use callbacks in included files

### PR DESCRIPTION
**Pull request by marc2k3**
Not tested yet. Will confirm later.

### CODE REVIEW

**Comment by TheQwertiest** [comment]
Ha... Seems I missed quite a lot >_<"" Thanks!

**Comment by TheQwertiest** [comment]
No problem, take your time, I still have enough tasks to do to keep me occupied =)

**Comment by marc2k3** [comment]
I need to restore my original seekbar.js and volume.js files. With your updated versions, the timers and tooltips are just plain broken and I don't really have the inclination to pick apart other people's code to figure out what is going on.

**Comment by TheQwertiest** [comment]
Well, I will probably just keep using a separate script folder for CaTRoX, otherwise I doubt I'll ever fix Brett's script cause of the messed up combination of engine changes + script changes + unfamiliar codebase.

**Comment by marc2k3** [comment]
I've tested what I can and it's all working except button tooltips. I think that's down to your changes in helpers but I've left it alone.

**Comment by TheQwertiest** [comment]
Thanks! I will merge and test it tomorrow

**Comment by marc2k3** [comment]
I forgot to test my thumbs script and having tried it just now... the component crashes! I'll submit a proper bug report later.

**Comment by TheQwertiest** [comment]
Do you think you can reproduce it? Or describe the steps that you performed that lead to it?

**Comment by marc2k3** [comment]
I know how annoying it is to get reports that you can't reproduce so sorry about that. 

It had nothing to do with the internet side of things - I was testing local images first but I can't seem to trigger it again.

**Comment by marc2k3** [comment]
I've ported JSPlaylist but it needs #6 addressing to work properly. Currently, the background image option doesn't work.

**Comment by marc2k3** [comment]
I'm done with this. The above issue with JSplaylist is fixed and if I port the remaining 3 JS-Smooth scripts, I'll submit a new PR.

**Comment by TheQwertiest** [comment]
Thanks!!!

**Pull request merged**
