### PR TITLE
Quick fix Display > Album Art Grid Mode crash

### PR DESCRIPTION
**Pull request by smoralis**

### CODE REVIEW

**Comment by marc2k3** [comment]
A better fix is to return from on_size if window.Width/window.Height is zero which is what happens on startup and why the script works if you reload manually.

This bug went unnoticed on JSP because if a C++ function like Resize expects an unsigned int (positive number) and you pass it a negative, it automatically gets converted to UINT_MAX (4 billion odd or `Math.pow(2,32) - 1` to be precise). While that's an insane value, the component seems to handle it OK! Clearly negative numbers are handled differently in SMP and it's why the function chokes. Perhaps some sanity checking would be the "real" fix.

**Comment by smoralis** [comment]
The PR is a quick fix, harmless bypass IMO  until a proper  fix with sanity checking is implemented as you described. 
Thanks for the info.

**Comment by TheQwertiest** [comment]
Hm... Maybe I can fix it on SMP side, so that workarounds like these would not be needed anymore. But we'll see...

@smoralis I think it should be implemented like here (https://github.com/marc2k3/foo_jscript_panel/commit/810837452bffd652f453a9fdc6ec35acdac0c199), since similar problems might arise eventually in other parts of the script. Such check is quite a common pattern in WSH/JSP/SMP scripts actually =)

**Comment by smoralis** [comment]
PR modified using sanity check in on_size as recommended.

**Comment by TheQwertiest** [comment]
Thanks!

**Pull request merged**
